[options]
admin_passwd = $pbkdf2-sha512$600000$ZMy5NwbAmFNK6R3D.H8PwQ$2nXa9zqsKZtpWG2dfSyHW.D0n9erTi.RF/jtMAgzd0JvqbVL/hmn13Atmfp8LRzAeJ9lzPrN3PMaoTAaMXINwQ

addons_path = ./addons,./dev_addons,./enterprise
bin_path = C:/Program Files/wkhtmltopdf/bin