[options]
admin_passwd = admin123
db_port = False
db_user = odoo
db_password = odoo
addons_path = /opt/odoo/odoo/addons,/opt/odoo/odoo/develop,/opt/odoo/odoo/enterprise
default_productivity_apps = True
log_file = /var/log/odoo/odoo.log
xmlrpc_port = 7958
data_dir = /opt/odoo/.local/share/Odoo
gevent_port = 8072
proxy_mode = True
limit_memory_hard = 0
limit_memory_soft = 0
limit_request = 8192
limit_time_cpu = 7500
limit_time_real = 8000
max_cron_threads = 1
workers = 17