# -*- coding: utf-8 -*-
from . import product_template
from . import hr_employee
from . import stock_picking
from . import mrp_production
from . import summary_output_daily_work
from . import summary_output_spreadsheet
from . import total_amount_received_byday
from . import final_total
from . import employee_enjoys
from . import enter_daily_work_output_other
from . import change_manual_worker_coefficient_byday
from . import config_classification
from . import employee_classification
from . import day_labor
from . import stock_warehouse
from . import trp_approve_history
from . import trp_approve_config_line
from . import advance_salary_summary
from . import hr_payslip_run
from . import hr_payslip_line
from . import hr_payslip
from . import mrp_bom
