from . import npk_weighing_history
from . import stock_picking
from . import sale_vehicle_in_out
from . import sale_vehicle_in_out_line
from . import sale_vehicle_mapping
from . import res_partner
from . import sale_order
from . import purchase_order
from . import mrp_production
from . import mrp_bom
from . import mrp_bom_tags
from . import npk_weighing_factory
from . import npk_weighing_machine
from . import ccv_mrp_plan_export
from . import ccv_sale_plan_export_line2
from . import stock_weighing_order
from . import rp_san_luong_nhap_xuat
from . import trp_approve_history
from . import trp_approve_config_line

from . import rp_san_luong_nhap_xuat_bocxep
