# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    "name": "CCV: Chỉnh sửa trường thông tin",
    "version": "1.3",
    "category": "",
    "description": """Chỉnh sửa trường thông tin""",
    "depends": [
        "web",
        "base",
        "stock_landed_costs",
        "biz_ccv_sale",
        "biz_client_ccv",
        "approvals",
        "biz_ccv_approvals",
        "hr_holidays",
        "sales_team",
        "purchase",
        "fleet",
        "mrp",
        # "hr_payroll",
        "ccv_bao_cao",
        "account_accountant",
        "biz_to_stock_backdate",
        'account_asset',
        "biz_viettel_sinvoice_v2",
        "biz_production_salary",
        "sale_invoice_product_image_app",
    ],
    "data": [
        "data/server_actions.xml",
        "data/parameter.xml",
        # "data/groups.xml",
        # "data/rule.xml",
        "security/ir.model.access.csv",
        "wizards/create_picking_wizard_view.xml",
        "wizards/create_mrp_wizard_view.xml",
        "wizards/remove_internal_picking_mrp_wizard_view.xml",
        "views/views.xml",
        "views/stock_picking.xml",
        "views/stock_quant.xml",
        "views/sale_order.xml",
        "views/approvals_category.xml",
        "views/approvals.xml",
        "views/hr_leave.xml",
        "views/purcharse_order.xml",
        "views/crm_team.xml",
        "views/stock_move.xml",
        "views/stock_move_line.xml",
        "views/sale_report.xml",
        "views/approval_category.xml",
        "views/approval_product_line.xml",
        "views/fleet.xml",
        "views/viettel_sinvoice_view.xml",
        "views/mrp.xml",
        "views/hr_payslip_run.xml",
        "views/res_partner.xml",
        "views/account_move.xml",
        "views/res_bank.xml",
        "views/picking_type_mapping_views.xml",
        "views/product_template.xml",
        "report/phieu_xuat_kho/document.xml",
        "report/phieu_xuat_kho/template.xml",
        "report/rp_plant_yield_charge_daily_work/document.xml",
        "report/rp_plant_yield_charge_daily_work/template.xml",
        "report/bao_cao_ccv_report.xml",
        "report/de_xuat_thue_xe/rent_proposal_template.xml",
        "report/de_xuat_phat_sinh_hang_ban.xml",
        "report/phieu_de_xuat_dat_bao_bi.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ccv_custom_field/static/src/**/*",
        ],
    },
    "installable": True,
    "license": "LGPL-3",
    'sequence': -100,
}
