# -*- coding: utf-8 -*-
{
    'name': 'CCV Báo cáo',
    'summary': "CCV Báo cáo",
    'description': "",
    'category': 'Customize/Report',
    'version': '1.0',
    'author': 'CCV',
    'depends': [
        'mrp',
        'crm',
        'sale_management',
        'trp_approve',
        'report_py3o',
        'report_xlsx',
        'stock',
        'approvals',
        'account_reports',
    ],
    'sequence': 1,
    'data': [
        'data/res_groups_views.xml',
        'data/parameter.xml',
        'security/ir.model.access.csv',
        'wizard/create_child_move_wizard_views.xml',
        'views/packaging_dashboard_views.xml',
        'views/account_payment_views.xml',
        'views/alpha_report_views.xml',
        'views/chi_tiet_cong_no_phai_tra.xml',
        'views/chi_tiet_cong_no_phai_thu.xml',
        'views/tong_hop_cong_no_phai_thu.xml',
        'views/so_chi_tiet_ke_toan_quy_tien_mat.xml',
        'views/giay_thanh_toan_tien_tam_ung.xml',
        'views/bao_cao_so_du_ngan_hang.xml',
        'views/danh_sach_chi_tiet_von_tu_co.xml',
        'views/stock_quant_views.xml',
        'views/account_account_views.xml',
        'views/res_config_settings_views.xml',
        'views/sale_teams_views.xml',
        'reports/header_views.xml',
        'reports/tong_hop_cong_no_nhan_vien.xml',
        'reports/chi_tiet_cong_no_phai_tra.xml',
        'reports/chi_tiet_cong_no_phai_thu.xml',
        'reports/tong_hop_cong_no_phai_thu.xml',
        'reports/so_chi_tiet_ke_toan_quy_tien_mat.xml',
        'reports/ccv_so_chi_tiet_ke_toan_quy_tien_mat_new.xml',
        'reports/giay_thanh_toan_tien_tam_ung.xml',
        'reports/giay_bao_co.xml',
        'reports/giay_bao_no.xml',
        'reports/bao_cao_so_du_ngan_hang.xml',
        'reports/danh_sach_chi_tiet_von_tu_co.xml',
        'reports/bien_ban_kiem_ke_vat_tu_hang_hoa.xml',
        'reports/mrp_production_views.xml',
        'reports/hr_expense_sheet_views.xml',
        'reports/phieu_thu.xml',
        'reports/phieu_chi.xml',
        'reports/vp_bank.xml',
        'reports/phieu_thu_hoa_don.xml',
        'reports/phieu_chi_hoa_don.xml',
        'reports/chi_tiet_cong_no_phai_thu_tax.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ccv_sql/static/src/xml/packaging_dashboard.xml',
            'ccv_sql/static/src/js/packaging_dashboard.js',
            'ccv_sql/static/src/xml/account_move_tree_buttons.xml',
            'ccv_sql/static/src/js/account_move_tree_buttons.js',
            # 'ccv_sql/static/src/js/stock_quant.js',
            # 'ccv_sql/static/src/xml/stock_quant_views.xml',
            'ccv_sql/static/src/xml/stock_orderpoint_list_buttons.xml',
            'ccv_sql/static/src/js/stock_orderpoint_list_controller.js',
            'ccv_sql/static/src/xml/account_reconciliation.xml',
            'ccv_sql/static/src/js/account_reconciliation.js',
        ],
    },
}
