from . import hr_allowances
from . import hr_deduction
from . import hr_payroll_update
from . import hr_working_day
from . import hr_contract
from . import hr_payslip
from . import hr_employee
from . import config_salary_insurence_union_dues
from . import ir_model_data
