# -*- coding: utf-8 -*-
{
    'name': 'Bizapps - KPI Business Salary',
    'version': '16.0.0.1',
    'category': 'Tools',
    'description': "",
    'author': 'support@bizapps.vn',
    'website': 'https://www.bizapps.vn',
    'depends': ['base','biz_business_salary','biz_kpi_scorecard','ccv_sale','report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'data/rule.xml',
        'report/report.xml',
        'views/salary_bonus_commission.xml',
        'views/salary_commission_setup.xml',
        'views/salary_commercial_discount_detail.xml',
        'views/salary_customer_open_list.xml',
        'views/salary_employee_commission.xml',
        'views/salary_humic_discount.xml',
        'views/salary_humic_sales_detail.xml',
        'views/salary_personnel_commission.xml',
        'views/salary_plan_sales.xml',
        'views/salary_sales_commission_employee.xml',
        'views/salary_sales_commission.xml',
        'views/salary_sales_discount.xml',
        'views/salary_sales_summary_line.xml',
        'views/salary_sales_summary_detail_line.xml',
        'views/salary_sales_summary_total_line.xml',
        'views/salary_commission_calculation.xml',
        'views/salary_commission_result.xml',
        'views/res_config_settings.xml',
        'views/uom_uom.xml',
        'views/salary_sales_summary.xml',
        'views/actions.xml',
        'views/kpi_business_salary.xml',
    ],
    'installable': True,
    'application': True
    ,
    "license": "OPL-1",
    'assets': {},
}
