{
    "name": "Bizapps - Details Purchase Report",
    "summary": "",
    "version": "16.0.0.1",
    'website': "https://bizapps.vn/ung-dung",
    'author': "support@bizapps.vn",
    'company': 'Bizapps',
    "category": "Purchase",
    "license": "OPL-1",
    "application": False,
    "installable": True,
    "depends": ["base","purchase","report_xlsx", "biz_ccv_purchase", "trp_approve", "ccv_report_stock_order", "ccv_sql"],
    "data": [
        "security/ir.model.access.csv",
        "data/parameter.xml",
        "report/report_action.xml",
        "report/details_purchase_report_template.xml",
        "report/details_purchase_book_template.xml",
        "report/details_internal_tf_book_template.xml",
        "wizards/wz_select_time_report_view.xml",
        "views/details_purchase_book_line.xml",
        "views/details_purchase_book.xml",
        "views/details_internal_tf_book.xml",
        "views/details_stock_order_book.xml",
        "views/details_accounts_payable_book.xml",
        "views/summary_accounts_payable_book.xml",
        "report/details_stock_order_book_template.xml",
        "report/details_accounts_payable_book_template.xml",
        "report/summary_accounts_payable_book_template.xml",
    ],
}
