{
    'name': 'Attachment Manager',
    'version': '19.0.1.0.0',
    'category': 'Tools',
    'summary': 'Dynamic attachment manager system with configurable keywords and activities',
    'description': """Attachment Manager for Odoo""",
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'security/attachment_manager_rules.xml',
        'wizards/attachment_move_trash.xml',
        'wizards/attachment_restore_selected.xml',
        'views/attachment_views.xml',
        'views/menu.xml',
        'data/cron.xml',
    ],
    'installable': True,
    'auto_install': False,
}
