# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    "name": "CCV: Kết nối API",
    "version": "1.3",
    "category": "API",
    "description": """Kết nối API""",
    'depends': ['mail','ccv_plan_mrp_sale','biz_conveyor_picking', 'website_sale', 'trp_approve'],
    'data': [
        'data/parameter.xml',
        'data/sale_vehicle_conveyor_mapping_data.xml',
        'data/cron.xml',
        'data/ir_sequence_data.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'report/bao_cao_ccv_report.xml',
        'report/rp_san_luong_nhap_xuat_pdf.xml',
        'report/bao_cao_ccv_report_bocxep.xml',
        'report/rp_san_luong_nhap_xuat_bocxep_pdf.xml',
        # 'views/stock_picking.xml',
        'views/ccv_mrp_plan_export.xml',
        'wizards/sale_vehicle_in_out_print_wizard.xml',
        'views/sale_vehicle_in_out_views.xml',
        'views/sale_vehicle_in_out_line_views.xml',
        'views/sale_vehicle_in_out_readonly_views.xml',
        'views/sale_vehicle_mapping_views.xml',
        'views/mrp_production_views.xml',
        'views/npk_weighing_history.xml',
        'views/res_partner.xml',
        'views/sale_order.xml',
        'views/purchase_order.xml',
        'views/mrp_bom_tags_views.xml',
        'views/mrp_bom_views.xml',
        'wizards/sale_vehicle_in_out_wizard.xml',
        'wizards/rp_tf_vehicel_in_out_wizard.xml',
        'wizards/check_request_api_wizard.xml',
        'views/rp_san_luong_nhap_xuat.xml',
        'views/rp_san_luong_nhap_xuat_bocxep.xml',
        'views/menu.xml',
        'views/sale_vehicle_dashboard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ccv_api_connector/static/src/js/weighing_auto_refresh.js',
            'ccv_api_connector/static/src/css/vehicle_dashboard.css',
            'ccv_api_connector/static/src/js/vehicle_dashboard.js',
            'ccv_api_connector/static/src/xml/vehicle_dashboard.xml',
        ],
    },
    'application': True,
    "installable": True,
    "license": "LGPL-3",
}
