# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    'name': 'CCV Báo cáo',
    'version': '1.3',
    'category': 'Accounting',
    'description': """CCV Báo cáo""",
    'depends': [
        'account',
        'ccv_sql',
        'report_py3o',
        'sales_team',
        'sale_management',
        'biz_ccv_sale',
        'approvals',
        'biz_payment_request',
        'biz_ccv_account',
        'hr_payroll',
        'ccv_payment_interest',
        'sale_stock',
    ],
    'data': [
        'data/transport_data.xml',
        'data/parameter.xml',
        # 'data/rule.xml',
        'security/ir.model.access.csv',
        'views/beta_views.xml',
        'views/report_views.xml',
        'views/hr_expense_sheet_views.xml',
        'report/report_header.xml',
        'report/giay_de_nghi_thanh_toan/document.xml',
        'report/giay_de_nghi_thanh_toan/template.xml',
        'report/bao_cao_ccv_report.xml',
        'report/lenh_dieu_dong_xe_di_cong_tac.xml',
        'views/report_sale.xml',
        'views/sale_order_line_report.xml',
        'views/approvals.xml',
        'views/sale_order.xml',
        'views/res_partner.xml',
        'views/res_company.xml',
        'views/purchase_order.xml',
        'views/ccv_data_src.xml',
        'wizards/stock_move_wizard_view.xml',
        'wizards/salary_payment_list_wizard_view.xml',
        'wizards/rp_internal_tf_wizard_views.xml',
        'wizards/rp_production_report_wizard_views.xml',
        'views/rp_production_report_views.xml',
        'report/rp_production_report_pdf.xml',
        'views/rp_thu_tien_report_views.xml',
        'report/rp_thu_tien_report_pdf.xml',
        'wizards/rp_internal_tf_materials_wizard.xml',
        'wizards/quotation_wizard_view.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
